//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABSA.PropertySvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PropertySvcRef.IProperty")]
    public interface IProperty {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty/Login", ReplyAction="http://tempuri.org/IProperty/LoginResponse")]
        bool Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty/Login", ReplyAction="http://tempuri.org/IProperty/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty/Register", ReplyAction="http://tempuri.org/IProperty/RegisterResponse")]
        string Register(string name, string surname, string email, string password, string type, string contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty/Register", ReplyAction="http://tempuri.org/IProperty/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string name, string surname, string email, string password, string type, string contact);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPropertyChannel : ABSA.PropertySvcRef.IProperty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PropertyClient : System.ServiceModel.ClientBase<ABSA.PropertySvcRef.IProperty>, ABSA.PropertySvcRef.IProperty {
        
        public PropertyClient() {
        }
        
        public PropertyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PropertyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PropertyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public string Register(string name, string surname, string email, string password, string type, string contact) {
            return base.Channel.Register(name, surname, email, password, type, contact);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string name, string surname, string email, string password, string type, string contact) {
            return base.Channel.RegisterAsync(name, surname, email, password, type, contact);
        }
    }
}
